import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,ShoppingCart,Package,MoreHorizontal,Plus,ChevronRight,AlertTriangle,TrendingUp,Receipt,Truck,Calculator,MessageCircle,Search,X,Check,LogOut,Users,BarChart3,Settings}from"lucide-react";
import"./styles.css";

const money=n=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(n)||0);
const api=async(path,opts={})=>{const token=localStorage.getItem("shop_token");const r=await fetch(path,{...opts,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||"Request failed");return j};
function App(){
 const[token,setToken]=useState(localStorage.getItem("shop_token")),[authMode,setAuthMode]=useState("login");
 if(!token)return <Auth mode={authMode} setMode={setAuthMode} onAuth={t=>{localStorage.setItem("shop_token",t);setToken(t)}}/>;
 return <Dashboard logout={()=>{localStorage.removeItem("shop_token");setToken(null)}}/>
}
function Auth({mode,setMode,onAuth}){const[f,setF]=useState({shopName:"Demo Home Store",name:"Shop Owner",email:"owner@example.com",password:"password123",phone:""}),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await api(mode==="login"?"/api/auth/login":"/api/auth/register",{method:"POST",body:JSON.stringify(f)});onAuth(r.token)}catch(e){setErr(e.message)}finally{setBusy(false)}};return <div className="auth"><div className="authbox"><div className="logo">S</div><p className="eyebrow">Retail business OS</p><h1>{mode==="login"?"Welcome back":"Create your shop"}</h1><p className="muted">{mode==="login"?"Sign in to your business control center.":"Start managing sales, stock and profit in one place."}</p><form onSubmit={submit}>{mode==="register"&&<><label>Shop name<input value={f.shopName} onChange={e=>setF({...f,shopName:e.target.value})}/></label><label>Your name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label></>}<label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{mode==="register"&&<label>Phone <small>(optional)</small><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label>}{err&&<div className="error">{err}</div>}<button className="primary wide" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create shop"}</button></form><button className="switch" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create a new shop":"I already have an account"}</button></div></div>}
function Dashboard({logout}){const[tab,setTab]=useState("home"),[d,setD]=useState(null),[dash,setDash]=useState(null),[modal,setModal]=useState(null),[toast,setToast]=useState(""),[online,setOnline]=useState(navigator.onLine);const load=async()=>{try{const [a,b]=await Promise.all([api("/api/data"),api("/api/dashboard")]);setD(a);setDash(b.dashboard)}catch(e){if(e.message==="Unauthorized")logout();else notify(e.message)}};useEffect(()=>{load();const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener("online",on);addEventListener("offline",off);if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});return()=>{removeEventListener("online",on);removeEventListener("offline",off)}},[]);const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2300)};const refresh=()=>load();
 if(!d||!dash)return <div className="loading">Loading your shop…</div>;
 const action=(type)=>setModal(type);
 return <div className="app"><header><div className="brand"><div className="logo">S</div><div><b>Shop Control</b><small>Business control center</small></div></div><div className="righthead"><span className="status"><i className={online?"on":""}/>{online?"Online":"Offline"}</span><button className="logout" onClick={logout}><LogOut size={15}/></button></div></header><main>
 {tab==="home"&&<Home d={d} dash={dash} nav={setTab} sale={()=>action("sale")}/>}
 {tab==="sales"&&<Sales d={d} sale={()=>action("sale")}/>}
 {tab==="inventory"&&<Inventory d={d} add={()=>action("product")} restock={id=>action({type:"restock",id})}/>}
 {tab==="customers"&&<Customers d={d}/>}
 {tab==="more"&&<More d={d} open={action}/>}
 </main><nav><N icon={<LayoutDashboard/>} t="Home" a={tab==="home"} c={()=>setTab("home")}/><N icon={<ShoppingCart/>} t="Sales" a={tab==="sales"} c={()=>setTab("sales")}/><button className="fab" onClick={()=>action("sale")}><Plus/></button><N icon={<Package/>} t="Stock" a={tab==="inventory"} c={()=>setTab("inventory")}/><N icon={<MoreHorizontal/>} t="More" a={tab==="more"} c={()=>setTab("more")}/></nav>{modal&&<Modal type={modal} d={d} close={()=>setModal(null)} refresh={refresh} notify={notify}/>} {toast&&<div className="toast"><Check size={16}/>{toast}</div>}</div>}
function N({icon,t,a,c}){return <button className={a?"active":""} onClick={c}>{icon}<span>{t}</span></button>}
function Home({d,dash,nav,sale}){return <Page eyebrow="Business control center" title="Good morning 👋" sub="Here’s what needs your attention today." action={sale}><div className="metrics"><M l="Today's sales" v={money(dash.todaySales)} t={`${dash.todayTransactions} transactions`}/><M l="This month's sales" v={money(dash.monthSales)} t={`${dash.monthTransactions} transactions`}/><M l="Gross profit" v={money(dash.monthProfit)} t="Before expenses"/><M l="Expenses" v={money(dash.monthExpenses)} t="This month"/></div><Section title="Today's attention"><div className="attention"><A icon={<AlertTriangle/>} title={`${dash.lowStock} products need attention`} text={`${dash.outOfStock} are out of stock`} c={()=>nav("inventory")}/><A icon={<Users/>} title="Customer follow-ups" text="Turn past buyers into repeat sales" c={()=>nav("customers")}/><A icon={<TrendingUp/>} title="Profit visibility" text="Every sale now calculates gross profit"/></div></Section><Section title="Stock watch" sub="Products at or below their reorder level"><div className="card">{d.products.filter(p=>p.stock<=p.reorder_level).map(p=><Row p={p} key={p.id}/>)}</div></Section><Section title="Quick actions"><div className="quick"><Q icon={<Receipt/>} t="Add expense"/><Q icon={<Truck/>} t="Restock"/><Q icon={<Calculator/>} t="Profit calculator"/><Q icon={<MessageCircle/>} t="WhatsApp post"/></div></Section></Page>}
function Page({eyebrow,title,sub,action,children}){return <div className="page"><div className="hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{sub}</p></div>{action&&<button className="primary" onClick={action}><Plus size={17}/> Record sale</button>}</div>{children}</div>}
function M({l,v,t}){return <div className="metric"><span>{l}</span><strong>{v}</strong><small>{t}</small></div>}
function Section({title,sub,children}){return <section><div className="sh"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div></div>{children}</section>}
function A({icon,title,text,c}){return <button className="attention" onClick={c}><div className="aicon">{icon}</div><div><b>{title}</b><p>{text}</p></div><ChevronRight/></button>}
function Q({icon,t}){return <button className="q"><div>{icon}</div><span>{t}</span><ChevronRight size={15}/></button>}
function Row({p}){let cls=p.stock===0?"red":p.stock<=p.reorder_level?"amber":"green";return <div className="row"><div className="picon"><Package size={18}/></div><div className="pinfo"><b>{p.name}</b><span>{p.category} · Sell {money(p.price)} · Cost {money(p.cost)}</span></div><em className={cls}>{p.stock===0?"Out of stock":`Reorder · ${p.stock}`}</em></div>}
function Sales({d,sale}){return <Page eyebrow="Sales" title="Sales history" sub="Every transaction is stored in your shop account." action={sale}><div className="summary"><div><span>Total sales</span><b>{money(d.sales.reduce((a,s)=>a+s.total,0))}</b></div><div><span>Transactions</span><b>{d.sales.length}</b></div><div><span>Gross profit</span><b>{money(d.sales.reduce((a,s)=>a+s.profit,0))}</b></div></div><div className="card">{d.sales.map(s=><div className="row" key={s.id}><div className="picon"><ShoppingCart size={18}/></div><div className="pinfo"><b>{s.product_name} × {s.qty}</b><span>{s.payment} · {s.customer_name||"Walk-in"} · {new Date(s.created_at).toLocaleDateString()}</span></div><strong>{money(s.total)}<small className="green">+{money(s.profit)}</small></strong></div>)}</div></Page>}
function Inventory({d,add,restock}){const[q,setQ]=useState("");let ps=d.products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));return <Page eyebrow="Inventory" title="Stock control" sub="Know what you have, what it costs and what to reorder."><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></div><button className="primary" onClick={add}><Plus size={17}/> Add</button></div><div className="card">{ps.map(p=><div className="row" key={p.id}><div className="picon"><Package size={18}/></div><div className="pinfo"><b>{p.name}</b><span>{p.category} · Sell {money(p.price)} · Cost {money(p.cost)}</span></div><em className={p.stock===0?"red":p.stock<=p.reorder_level?"amber":"green"}>{p.stock} units</em><button className="smallbtn" onClick={()=>restock(p.id)}>Restock</button></div>)}</div></Page>}
function Customers({d}){return <Page eyebrow="Customers" title="Customer relationships" sub="Purchase history that helps you sell again."><div className="card">{d.customers.map(c=><div className="crow" key={c.id}><div className="avatar">{c.name[0]}</div><div className="pinfo"><b>{c.name}</b><span>{c.phone||"No phone"} · {c.orders} orders</span></div><div className="cr"><b>{money(c.spent)}</b><small>{c.last_purchase?new Date(c.last_purchase).toLocaleDateString():"No purchase"}</small></div></div>)}</div></Page>}
function More({d,open}){return <Page eyebrow="Business tools" title="Run the whole shop" sub="Tools connected to your business data."><div className="toolgrid"><Tool icon={<Receipt/>} t="Expenses" s={`${d.expenses.length} recent records`} c={()=>open("expense")}/><Tool icon={<Truck/>} t="Suppliers" s={`${d.suppliers.length} supplier profiles`} c={()=>open("suppliers")}/><Tool icon={<Calculator/>} t="Profit calculator" s="Calculate true landed cost" c={()=>open("calculator")}/><Tool icon={<MessageCircle/>} t="WhatsApp Sales Machine" s="Generate product sales copy" c={()=>open("whatsapp")}/><Tool icon={<BarChart3/>} t="Reports" s="Sales, profit and expenses" c={()=>open("reports")}/><Tool icon={<Settings/>} t="Shop settings" s="Business profile and account" c={()=>open("settings")}/></div></Page>}
function Tool({icon,t,s,c}){return <button className="tool" onClick={c}><div className="ticon">{icon}</div><div><b>{t}</b><p>{s}</p></div><ChevronRight/></button>}

function Modal({type,d,close,refresh,notify}){if(typeof type==="object")return <Restock d={d} id={type.id} close={close} refresh={refresh} notify={notify}/>;if(type==="sale")return <Sale d={d} close={close} refresh={refresh} notify={notify}/>;if(type==="product")return <Product close={close} refresh={refresh} notify={notify}/>;if(type==="expense")return <Expense close={close} refresh={refresh} notify={notify}/>;if(type==="calculator")return <Calc d={d} close={close}/>;if(type==="whatsapp")return <WA d={d} close={close} notify={notify}/>;if(type==="suppliers")return <Simple title="Suppliers" close={close}>{d.suppliers.map(s=><div className="supplier" key={s.id}><b>{s.name}</b><span>{s.phone}</span><span>{s.products}</span><small>MOQ {s.moq} · Last price {s.last_price}</small></div>)}</Simple>;if(type==="reports")return <Simple title="Reports" close={close}><div className="report">{[["Sales",d.sales.reduce((a,s)=>a+s.total,0)],["Gross profit",d.sales.reduce((a,s)=>a+s.profit,0)],["Expenses",d.expenses.reduce((a,e)=>a+e.amount,0)],["Profit after expenses",d.sales.reduce((a,s)=>a+s.profit,0)-d.expenses.reduce((a,e)=>a+e.amount,0)]].map(x=><div><span>{x[0]}</span><b>{money(x[1])}</b></div>)}</div></Simple>;return <Simple title="Shop settings" close={close}><div className="settings"><span>Cloud account: active</span><span>Database: persistent</span><span>Offline shell: enabled</span><span>Authentication: JWT + hashed passwords</span></div></Simple>}
function Shell({title,close,children,save,saveText="Save"}){return <div className="overlay"><div className="modal"><div className="mhead"><div><p className="eyebrow">Shop Control</p><h2>{title}</h2></div><button className="iconbtn" onClick={close}><X/></button></div>{children}{save&&<button className="primary wide" onClick={save}><Check size={17}/>{saveText}</button>}</div></div>}
function Simple({title,close,children}){return <Shell title={title} close={close}>{children}</Shell>}
function Sale({d,close,refresh,notify}){const[p,setP]=useState(d.products.find(x=>x.stock>0)?.id||""),[q,setQ]=useState(1),[pay,setPay]=useState("Cash"),[c,setC]=useState("");const x=d.products.find(a=>a.id===p);const save=async()=>{try{await api("/api/sales",{method:"POST",body:JSON.stringify({productId:p,qty:q,payment:pay,customerName:c})});notify("Sale recorded ✓");close();refresh()}catch(e){notify(e.message)}};return <Shell title="Record sale" close={close} save={save} saveText="Complete sale"><label>Product<select value={p} onChange={e=>setP(e.target.value)}>{d.products.filter(x=>x.stock>0).map(x=><option value={x.id}>{x.name} · {x.stock} in stock</option>)}</select></label><div className="twocol"><label>Quantity<input type="number" min="1" max={x?.stock} value={q} onChange={e=>setQ(Math.max(1,Number(e.target.value)))}/></label><label>Payment<select value={pay} onChange={e=>setPay(e.target.value)}><option>Cash</option><option>Transfer</option><option>POS</option><option>Credit</option></select></label></div><label>Customer <small>(optional)</small><input value={c} onChange={e=>setC(e.target.value)} placeholder="Customer name"/></label>{x&&<div className="total"><span>Total</span><b>{money(x.price*q)}</b><small>Estimated profit {money((x.price-x.cost)*q)}</small></div>}</Shell>}
function Product({close,refresh,notify}){const[f,setF]=useState({name:"",category:"Bedding",stock:0,cost:0,price:0,reorderLevel:5});const save=async()=>{try{await api("/api/products",{method:"POST",body:JSON.stringify(f)});notify("Product added ✓");close();refresh()}catch(e){notify(e.message)}};return <Shell title="Add product" close={close} save={save}><label>Product name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="e.g. Glass Dinner Set"/></label><div className="twocol"><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Bedding</option><option>Kitchen</option><option>Bath</option><option>Other</option></select></label><label>Reorder level<input type="number" value={f.reorderLevel} onChange={e=>setF({...f,reorderLevel:Number(e.target.value)})}/></label></div><div className="twocol"><label>Opening stock<input type="number" value={f.stock} onChange={e=>setF({...f,stock:Number(e.target.value)})}/></label><label>Cost price<input type="number" value={f.cost} onChange={e=>setF({...f,cost:Number(e.target.value)})}/></label></div><label>Selling price<input type="number" value={f.price} onChange={e=>setF({...f,price:Number(e.target.value)})}/></label></Shell>}
function Restock({d,id,close,refresh,notify}){const p=d.products.find(x=>x.id===id),[q,setQ]=useState(10),[c,setC]=useState(p.cost);const save=async()=>{try{await api(`/api/products/${id}/restock`,{method:"POST",body:JSON.stringify({qty:q,cost:c})});notify("Stock updated ✓");close();refresh()}catch(e){notify(e.message)}};return <Shell title={`Restock ${p.name}`} close={close} save={save}><div className="total"><span>Current stock</span><b>{p.stock} units</b></div><div className="twocol"><label>Add units<input type="number" value={q} onChange={e=>setQ(Number(e.target.value))}/></label><label>New unit cost<input type="number" value={c} onChange={e=>setC(Number(e.target.value))}/></label></div></Shell>}
function Expense({close,refresh,notify}){const[f,setF]=useState({category:"Transport",amount:"",note:""});const save=async()=>{try{await api("/api/expenses",{method:"POST",body:JSON.stringify({...f,amount:Number(f.amount)})});notify("Expense added ✓");close();refresh()}catch(e){notify(e.message)}};return <Shell title="Add expense" close={close} save={save}><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{["Transport","Rent","Electricity","Staff salary","Packaging","Delivery","Advertising","Other"].map(x=><option>{x}</option>)}</select></label><label>Amount<input type="number" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})} placeholder="₦ 0"/></label><label>Note<input value={f.note} onChange={e=>setF({...f,note:e.target.value})} placeholder="What was this for?"/></label></Shell>}
function Calc({d,close}){const[p,setP]=useState(d.products[0]?.id),[t,setT]=useState(500),[o,setO]=useState(300),x=d.products.find(a=>a.id===p),land=(x?.cost||0)+Number(t)+Number(o),profit=(x?.price||0)-land;return <Shell title="Profit calculator" close={close}><label>Product<select value={p} onChange={e=>setP(e.target.value)}>{d.products.map(x=><option value={x.id}>{x.name}</option>)}</select></label><div className="twocol"><label>Transport / unit<input type="number" value={t} onChange={e=>setT(e.target.value)}/></label><label>Other / unit<input type="number" value={o} onChange={e=>setO(e.target.value)}/></label></div><div className="calc"><div><span>True landed cost</span><b>{money(land)}</b></div><div><span>Selling price</span><b>{money(x?.price)}</b></div><div><span>Profit / unit</span><b>{money(profit)}</b></div><div><span>Margin</span><b>{x?.price?Math.round(profit/x.price*100):0}%</b></div></div></Shell>}
function WA({d,close,notify}){const[p,setP]=useState(d.products[0]?.id),x=d.products.find(a=>a.id===p),copy=`✨ ${x?.name}\\n\\nUpgrade your home with our beautiful ${x?.name}.\\n\\n💰 ${money(x?.price)}\\n📦 ${x?.stock} available\\n\\nSend us a message to order today!`;return <Shell title="WhatsApp Sales Machine" close={close}><label>Product<select value={p} onChange={e=>setP(e.target.value)}>{d.products.map(x=><option value={x.id}>{x.name}</option>)}</select></label><div className="copybox">{copy}</div><div className="twocol"><button className="secondary" onClick={()=>navigator.clipboard?.writeText(copy).then(()=>notify("Copied ✓"))}>Copy</button><button className="primary" onClick={()=>{navigator.share?.({text:copy});notify("Ready to share ✓")}}>Share</button></div></Shell>}
createRoot(document.getElementById("root")).render(<App/>);